# Generated by Django 4.2.3 on 2023-07-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_team_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutPage",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="content",
            new_name="body_text",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="date_posted",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="author",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_name",
            field=models.CharField(default="anonymous", max_length=100),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_photo",
            field=models.ImageField(
                default="static/gt_logo.png", upload_to="blog_covers/"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=2000),
        ),
    ]
