# Generated by Django 4.2.3 on 2023-07-31 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("green_team_app", "0004_rename_role_teammember_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="other_author",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="green_team_app.teammember",
            ),
        ),
    ]
