# Generated by Django 4.2.3 on 2023-08-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_team_app", "0006_blogpost_cover_source_alter_blogpost_cover_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("instagram_link", models.URLField(blank=True)),
                ("google_classroom_link", models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="MailingListEmail",
        ),
    ]
