# Generated by Django 4.2.3 on 2023-08-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_team_app", "0007_footer_delete_mailinglistemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="footer",
            name="google_classroom_link",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="instagram_link",
        ),
        migrations.AddField(
            model_name="footer",
            name="social_media_links",
            field=models.ManyToManyField(to="green_team_app.socialmedialink"),
        ),
    ]
