# Generated by Django 4.2.3 on 2023-08-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "green_team_app",
            "0008_socialmedialink_remove_footer_google_classroom_link_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmedialink",
            old_name="url",
            new_name="link",
        ),
    ]
