# Generated by Django 4.2.3 on 2023-08-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("green_team_app", "0010_projects"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
    ]
